import type { Preset } from "./presets";

export const BUILT_IN_PRESETS: Preset[] = [
  {
    id: "default",
    name: "Recommended — Best Available",
    description: "Best video + audio from the source (no size limits)",
    isBuiltIn: true,
    args: ["-f", "bestvideo+bestaudio/best"],
  },
  {
    id: "recommended-1080p",
    name: "Recommended — Best Available (Up to 1080p)",
    description: "Best video up to 1080p + best audio",
    isBuiltIn: true,
    args: ["-f", "bestvideo[height<=1080]+bestaudio/best"],
  },
  {
    id: "high-quality",
    name: "Recommended — Best Available (Up to 4K)",
    description: "Best video up to 2160p + best audio",
    isBuiltIn: true,
    args: ["-f", "bestvideo[height<=2160]+bestaudio/best"],
  },
  {
    id: "whatsapp-optimized",
    name: "Compatibility — WhatsApp Optimized (H.264 + AAC)",
    description: "Optimized for WhatsApp (1080p, compatible codecs, fast start)",
    isBuiltIn: true,
    args: [
      "-f",
      "bv[height<=1080][ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[height<=1080][vcodec^=avc1]+ba/b[height<=1080][ext=mp4][vcodec^=avc1]/b[height<=1080]",
      "--merge-output-format",
      "mp4",
      "--postprocessor-args",
      "VideoConvertor:-c:v libx264 -pix_fmt yuv420p -c:a aac -b:a 128k -crf 23 -preset slow -movflags +faststart"
    ],
  },
  {
    id: "whatsapp",
    name: "Compatibility — MP4 (H.264 + AAC)",
    description: "Most compatible choice for phones, social apps, and editors",
    isBuiltIn: true,
    args: [
      "-f",
      "bv[ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[vcodec^=avc1]+ba/b[ext=mp4][vcodec^=avc1]/b",
      "--merge-output-format",
      "mp4"
    ],
  },
  {
    id: "mp4-best",
    name: "Compatibility — Best MP4 (Any Codec)",
    description: "Highest quality MP4; codec may vary by source",
    isBuiltIn: true,
    args: ["-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]", "--merge-output-format", "mp4"],
  },
  {
    id: "webm-best",
    name: "Web — Best WebM (VP9/AV1)",
    description: "Best WebM quality; not ideal for most editors",
    isBuiltIn: true,
    args: ["-f", "bestvideo[ext=webm]+bestaudio[ext=webm]/best[ext=webm]"],
  },
  {
    id: "editors-capcut-1080p-mp4",
    name: "Editors — CapCut (1080p MP4 H.264 + AAC)",
    description: "Editing-friendly MP4 for CapCut; prefers H.264/AAC when available",
    isBuiltIn: true,
    args: [
      "-f",
      "bv[height<=1080][ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[height<=1080][vcodec^=avc1]+ba/b[height<=1080][ext=mp4]/b[height<=1080]",
      "--merge-output-format",
      "mp4",
    ],
  },
  {
    id: "editors-capcut-4k-mp4",
    name: "Editors — CapCut (4K MP4 H.264 + AAC)",
    description: "Editing-friendly MP4 for CapCut; prefers H.264/AAC when available",
    isBuiltIn: true,
    args: [
      "-f",
      "bv[height<=2160][ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[height<=2160][vcodec^=avc1]+ba/b[height<=2160][ext=mp4]/b[height<=2160]",
      "--merge-output-format",
      "mp4",
    ],
  },
  {
    id: "editors-premiere-ae-1080p-mp4",
    name: "Editors — Premiere/After Effects (1080p MP4 H.264 + AAC)",
    description: "Editing-friendly MP4 for Premiere/AE; prefers H.264/AAC when available",
    isBuiltIn: true,
    args: [
      "-f",
      "bv[height<=1080][ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[height<=1080][vcodec^=avc1]+ba/b[height<=1080][ext=mp4]/b[height<=1080]",
      "--merge-output-format",
      "mp4",
    ],
  },
  {
    id: "editors-premiere-ae-4k-mp4",
    name: "Editors — Premiere/After Effects (4K MP4 H.264 + AAC)",
    description: "Editing-friendly MP4 for Premiere/AE; prefers H.264/AAC when available",
    isBuiltIn: true,
    args: [
      "-f",
      "bv[height<=2160][ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[height<=2160][vcodec^=avc1]+ba/b[height<=2160][ext=mp4]/b[height<=2160]",
      "--merge-output-format",
      "mp4",
    ],
  },
  {
    id: "editors-prores-1080p-mov",
    name: "Editors Pro — ProRes 422 (1080p MOV)",
    description: "Transcodes to ProRes for smoother editing (large files; requires FFmpeg)",
    isBuiltIn: true,
    args: [
      "-f",
      "bestvideo[height<=1080]+bestaudio/best[height<=1080]",
      "--recode-video",
      "mov",
      "--postprocessor-args",
      "VideoConvertor:-c:v prores_ks -profile:v 3 -pix_fmt yuv422p10le -c:a pcm_s16le",
    ],
  },
  {
    id: "editors-prores-4k-mov",
    name: "Editors Pro — ProRes 422 (4K MOV)",
    description: "Transcodes to ProRes for smoother editing (huge files; requires FFmpeg)",
    isBuiltIn: true,
    args: [
      "-f",
      "bestvideo[height<=2160]+bestaudio/best[height<=2160]",
      "--recode-video",
      "mov",
      "--postprocessor-args",
      "VideoConvertor:-c:v prores_ks -profile:v 3 -pix_fmt yuv422p10le -c:a pcm_s16le",
    ],
  },
  {
    id: "video-only",
    name: "Video — Best Video Only",
    description: "Highest quality video stream without audio",
    isBuiltIn: true,
    args: ["-f", "bestvideo"],
  },
  {
    id: "audio-only",
    name: "Audio — Best Audio (Source)",
    description: "Highest bitrate audio stream; format may be Opus/WebM depending on source",
    isBuiltIn: true,
    args: ["-f", "bestaudio"],
  },
  {
    id: "flac",
    name: "Audio — FLAC (Lossless Convert)",
    description: "Converts best source audio to FLAC (no added loss; source may be lossy)",
    isBuiltIn: true,
    args: ["-f", "bestaudio", "-x", "--audio-format", "flac"],
  },
  {
    id: "wav",
    name: "Audio — WAV (Lossless Convert)",
    description: "Converts best source audio to WAV (no added loss; huge files; source may be lossy)",
    isBuiltIn: true,
    args: ["-f", "bestaudio", "-x", "--audio-format", "wav"],
  },
  {
    id: "alac",
    name: "Audio — ALAC (Lossless Convert)",
    description: "Converts best source audio to ALAC (no added loss; source may be lossy)",
    isBuiltIn: true,
    args: ["-f", "bestaudio", "-x", "--audio-format", "alac"],
  },
  {
    id: "mp3",
    name: "Audio — MP3 (High Quality)",
    description: "Converts best source audio to MP3 (lossy; requires FFmpeg)",
    isBuiltIn: true,
    args: ["-f", "bestaudio", "-x", "--audio-format", "mp3", "--audio-quality", "0"],
  },
];
