import type { Preset } from "./presets";

export const BUILT_IN_PRESETS: Preset[] = [
  {
    id: "default",
    name: "Best Video",
    description: "Highest available video and audio from the source.",
    isBuiltIn: true,
    group: "recommended",
    featured: true,
    args: ["-f", "bestvideo+bestaudio/best"],
    quickEligible: true,
  },
  {
    id: "default-subs",
    name: "Best Video + Subtitles",
    description: "Highest available video and audio with sidecar subtitles when available.",
    isBuiltIn: true,
    group: "recommended",
    featured: true,
    args: ["-f", "bestvideo+bestaudio/best"],
    quickEligible: true,
    subtitleMode: "on",
    subtitleSourcePolicy: "manual-then-auto",
    subtitleLanguageMode: "preferred",
    subtitleLanguages: ["en.*", "en"],
    subtitleFormat: "srt",
  },
  {
    id: "recommended-1080p",
    name: "Best Video (Up to 1080p)",
    description: "Highest available quality capped at 1080p.",
    isBuiltIn: true,
    group: "recommended",
    args: ["-f", "bestvideo[height<=1080]+bestaudio/best"],
    quickEligible: true,
  },
  {
    id: "high-quality",
    name: "Best Video (Up to 4K)",
    description: "Highest available quality capped at 4K.",
    isBuiltIn: true,
    group: "recommended",
    args: ["-f", "bestvideo[height<=2160]+bestaudio/best"],
    quickEligible: true,
  },
  {
    id: "whatsapp-optimized",
    name: "WhatsApp Ready",
    description: "Smaller MP4 tuned for WhatsApp sharing with H.264, AAC, and fast start.",
    isBuiltIn: true,
    group: "share",
    featured: true,
    args: [
      "-f",
      "bv[height<=1080][ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[height<=1080][vcodec^=avc1]+ba/b[height<=1080][ext=mp4][vcodec^=avc1]/b[height<=1080]",
      "--merge-output-format",
      "mp4",
      "--postprocessor-args",
      "VideoConvertor:-c:v libx264 -pix_fmt yuv420p -c:a aac -b:a 128k -crf 23 -preset slow -movflags +faststart",
    ],
    quickEligible: true,
  },
  {
    id: "whatsapp-optimized-subs",
    name: "WhatsApp Ready + Subtitles",
    description: "WhatsApp-ready MP4 with sidecar subtitles when available.",
    isBuiltIn: true,
    group: "share",
    args: [
      "-f",
      "bv[height<=1080][ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[height<=1080][vcodec^=avc1]+ba/b[height<=1080][ext=mp4][vcodec^=avc1]/b[height<=1080]",
      "--merge-output-format",
      "mp4",
      "--postprocessor-args",
      "VideoConvertor:-c:v libx264 -pix_fmt yuv420p -c:a aac -b:a 128k -crf 23 -preset slow -movflags +faststart",
    ],
    quickEligible: true,
    subtitleMode: "on",
    subtitleSourcePolicy: "manual-then-auto",
    subtitleLanguageMode: "preferred",
    subtitleLanguages: ["en.*", "en"],
    subtitleFormat: "srt",
  },
  {
    id: "whatsapp",
    name: "Compatible MP4",
    description: "Reliable MP4 choice for phones, social apps, and most editors.",
    isBuiltIn: true,
    group: "share",
    args: [
      "-f",
      "bv[ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[vcodec^=avc1]+ba/b[ext=mp4][vcodec^=avc1]/b",
      "--merge-output-format",
      "mp4",
    ],
    quickEligible: true,
  },
  {
    id: "mp4-best",
    name: "Best MP4",
    description: "Best MP4 output when you specifically want MP4.",
    isBuiltIn: true,
    group: "formats",
    args: ["-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]", "--merge-output-format", "mp4"],
    quickEligible: true,
  },
  {
    id: "webm-best",
    name: "Best WebM",
    description: "Best WebM quality for browsers and modern web playback.",
    isBuiltIn: true,
    group: "formats",
    args: ["-f", "bestvideo[ext=webm]+bestaudio[ext=webm]/best[ext=webm]"],
    quickEligible: true,
  },
  {
    id: "editors-capcut-1080p-mp4",
    name: "Editing MP4 (1080p)",
    description: "Editor-friendly MP4 for quick timeline work up to 1080p.",
    isBuiltIn: true,
    group: "editing",
    args: [
      "-f",
      "bv[height<=1080][ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[height<=1080][vcodec^=avc1]+ba/b[height<=1080][ext=mp4]/b[height<=1080]",
      "--merge-output-format",
      "mp4",
    ],
    quickEligible: false,
  },
  {
    id: "editors-capcut-4k-mp4",
    name: "Editing MP4 (4K)",
    description: "Editor-friendly MP4 for quick timeline work up to 4K.",
    isBuiltIn: true,
    group: "editing",
    args: [
      "-f",
      "bv[height<=2160][ext=mp4][vcodec^=avc1]+ba[ext=m4a]/bv[height<=2160][vcodec^=avc1]+ba/b[height<=2160][ext=mp4]/b[height<=2160]",
      "--merge-output-format",
      "mp4",
    ],
    quickEligible: false,
  },
  {
    id: "editors-prores-1080p-mov",
    name: "Editing ProRes (1080p)",
    description: "Transcodes to ProRes for smoother editing up to 1080p. Large files.",
    isBuiltIn: true,
    group: "editing",
    args: [
      "-f",
      "bestvideo[height<=1080]+bestaudio/best[height<=1080]",
      "--recode-video",
      "mov",
      "--postprocessor-args",
      "VideoConvertor:-c:v prores_ks -profile:v 3 -pix_fmt yuv422p10le -c:a pcm_s16le",
    ],
    quickEligible: false,
  },
  {
    id: "editors-prores-4k-mov",
    name: "Editing ProRes (4K)",
    description: "Transcodes to ProRes for smoother editing up to 4K. Huge files.",
    isBuiltIn: true,
    group: "editing",
    args: [
      "-f",
      "bestvideo[height<=2160]+bestaudio/best[height<=2160]",
      "--recode-video",
      "mov",
      "--postprocessor-args",
      "VideoConvertor:-c:v prores_ks -profile:v 3 -pix_fmt yuv422p10le -c:a pcm_s16le",
    ],
    quickEligible: false,
  },
  {
    id: "video-only",
    name: "Video Only",
    description: "Highest quality video stream without audio.",
    isBuiltIn: true,
    group: "formats",
    args: ["-f", "bestvideo"],
    quickEligible: true,
  },
  {
    id: "audio-only",
    name: "Source Audio",
    description: "Best available audio stream without converting it.",
    isBuiltIn: true,
    group: "audio",
    args: ["-f", "bestaudio"],
    quickEligible: true,
  },
  {
    id: "subtitles-only",
    name: "Subtitles Only",
    description: "Downloads subtitle files only, preferring manual captions and falling back to auto-generated captions.",
    isBuiltIn: true,
    group: "subtitles",
    featured: true,
    args: [],
    quickEligible: true,
    subtitleMode: "only",
    subtitleOnly: true,
    subtitleSourcePolicy: "manual-then-auto",
    subtitleLanguageMode: "preferred",
    subtitleLanguages: ["en.*", "en"],
    subtitleFormat: "srt",
  },
  {
    id: "flac",
    name: "Audio FLAC",
    description: "Converts best source audio to FLAC. No additional loss, but source may already be lossy.",
    isBuiltIn: true,
    group: "audio",
    args: ["-f", "bestaudio", "-x", "--audio-format", "flac"],
    quickEligible: false,
  },
  {
    id: "wav",
    name: "Audio WAV",
    description: "Converts best source audio to WAV. Huge files, but no additional loss.",
    isBuiltIn: true,
    group: "audio",
    args: ["-f", "bestaudio", "-x", "--audio-format", "wav"],
    quickEligible: false,
  },
  {
    id: "alac",
    name: "Audio ALAC",
    description: "Converts best source audio to ALAC. Great for Apple-focused lossless libraries.",
    isBuiltIn: true,
    group: "audio",
    args: ["-f", "bestaudio", "-x", "--audio-format", "alac"],
    quickEligible: false,
  },
  {
    id: "mp3",
    name: "Audio MP3",
    description: "Converts best source audio to high-quality MP3.",
    isBuiltIn: true,
    group: "audio",
    featured: true,
    args: ["-f", "bestaudio", "-x", "--audio-format", "mp3", "--audio-quality", "0"],
    quickEligible: true,
  },
];
